### ISSUE TITLE
Any update of this project?

### ISSUE THREAD

**Issue by LaynePeng** [dmikusa-pivotal/cf-maven-buildpack#2]
Hi, I find your project is excellent, which can save a lot of time of offline build. I notice that it is not update for more than 2 years. I wonder if any update or has it been moved to other repo?

**Comment by dmikusa-pivotal** [comment]
Hi, this build pack was more of an experiment than a long term project.  If it's something you're interested in, feel free to submit a PR or fork.  I see a couple forks already, maybe one of those is more up-to-date.
